# 必要语法解释

补充在完成作业过程中涉及到的语法。

## 向量、矩阵、张量

- 张量 (Tensor) 和向量 (Vector) 的区别
    - 向量 (Vector)：
    - 向量是一维数组，用于表示空间中的方向和大小。
    - 向量是数学概念，通常指具有大小和方向的量。
    - 在机器学习中，向量通常指一维张量。

- 张量 (Tensor)：
    - 张量是向量和矩阵的推广，可以是任意维度的数组。
    - 零维张量是标量，一维张量是向量，二维张量是矩阵，三维及以上称为多维张量。
    - 在深度学习中，张量是最基本的数据结构，用于存储和处理数据。


## repeat函数
在 PyTorch 中，repeat() 函数用于复制张量中的元素，沿指定维度扩展张量的形状。
```python
tensor.repeat(*sizes)
```

- 参数：*sizes 是一个或多个整数，指定每个维度上的重复次数。
- 返回：返回一个新的张量，其元素是原张量的重复。

In [2]:
# 1维张量重复
import torch

x = torch.tensor([1, 2, 3])
x = x.repeat(3) # 沿着第0维重复三次
print(x)

tensor([1, 2, 3, 1, 2, 3, 1, 2, 3])


In [5]:
# 2维张量重复
import torch

x = torch.tensor([[1, 2], [3, 4]]) # 从外往里，维度依次升高
print(x.repeat(2, 1)) # 第0维重复2次
print(x.repeat(1, 3)) # 第1维重复3次
x = x.repeat(2, 3)
print(x)

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])
tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])
tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])


## unsqueeze 函数
在 PyTorch 中，unsqueeze() 函数用于在张量的指定位置插入一个维度，其值为 1。这在需要调整张量形状以匹配特定操作（如广播）时非常有用。

```python
tensor.unsqueeze(dim)
```

- 参数：dim 是要插入新维度的位置（整数）。
- 返回：返回一个新的张量，其维度比原张量多 1。

In [12]:
# 一维张量 ➡️ 二维张量
import torch

x = torch.tensor([1, 2, 3]) # 在第几维插入维度，就将第几维的所有元素用列表[]包起来

print("在第0维插入维度：")
x1 = x.unsqueeze(0)
print(x1, x1.size())

print("在第1维插入维度：")
x2 = x.unsqueeze(1)
print(x2, x2.size())

在第0维插入维度：
tensor([[1, 2, 3]]) torch.Size([1, 3])
在第1维插入维度：
tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])


In [11]:
# 二维张量 ➡️ 三维张量
import torch

x = torch.tensor([[1, 2], [3, 4]])
print(x.shape)

x1 = x.unsqueeze(0)
print(x1, x1.size())

x2 = x.unsqueeze(1)
print(x2, x2.size())

x3 = x.unsqueeze(2)
print(x3, x3.shape)

torch.Size([2, 2])
tensor([[[1, 2],
         [3, 4]]]) torch.Size([1, 2, 2])
tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2])
tensor([[[1],
         [2]],

        [[3],
         [4]]]) torch.Size([2, 2, 1])


## squeeze 函数

与unsqueeze函数相反，该函数是删减特定维度。删除第几维，就去掉第几维的[]。

In [14]:
a = torch.tensor([1, 2, 3])     # 形状: [3]
b = torch.tensor([[4], [5], [6]])    # 形状: [2, 1]

# 错误：无法直接相加
# c = a + b

# 正确：调整 a 的形状为 [3, 1]
c = a.unsqueeze(1) + b
print(c)
# 输出:
# tensor([[5, 6, 7],
#         [6, 7, 8]])

tensor([[5],
        [7],
        [9]])


## 广播

在 PyTorch 中，广播（Broadcasting） 是一种强大的机制，允许不同形状的张量进行算术运算，而无需显式复制数据。

**广播的核心规则**

- 维度对齐：从最后一个维度开始向前比较，维度大小必须：
    - 相等，或
    - 其中一个为 1。
- 维度扩展：若某个张量的维度更少，则在左侧补 1，直到维度数匹配。
- 元素操作：每个维度上的操作会自动扩展到所有元素。

In [15]:
# 1. 向量与标量相加
# 2. 向量与矩阵相加
a = torch.tensor([1, 2, 3])     # 形状：[3]
b = torch.tensor([[10], [20]])  # 形状：[2, 1]

# 调整 a 的维度，在最前面加一维
# a.shape=(1, 3), b.shape=(2, 1)
# 广播后的形状：[2, 3]，每个维度将1维的值加到另一个的所有维度上
c = a.unsqueeze(0) + b
print(c, c.shape)

tensor([[11, 12, 13],
        [21, 22, 23]]) torch.Size([2, 3])


In [20]:
# 3. 三维张量的广播
a = torch.rand(3, 1, 4) # shape: (3, 1, 4)
b = torch.rand(1, 2, 4) # shape: (1, 2, 4)

c = a + b
print(c, c.shape)

tensor([[[0.3082, 0.4318, 0.7938, 0.9368],
         [0.4784, 0.9879, 0.7584, 0.7286]],

        [[1.0045, 0.2503, 0.9643, 1.0838],
         [1.1747, 0.8065, 0.9289, 0.8756]],

        [[1.0037, 0.4848, 0.9543, 0.5802],
         [1.1739, 1.0409, 0.9189, 0.3720]]]) torch.Size([3, 2, 4])


## expend 函数

在 PyTorch 中，expand() 用于扩展张量的形状，使其与目标形状匹配。与 repeat() 不同，expand() 不会复制实际数据，而是通过广播机制在逻辑上扩展张量。

```python
tensor.expand(*sizes)
```

- \*sizes：目标形状的元组，表示每个维度需要扩展的大小。
- 返回一个逻辑上扩展后的新张量，数据并未实际复制。

In [21]:
# 一维张量扩展
import torch

x = torch.tensor([1, 2, 3]) # shape=(3)
x1 = x.expand(2, 3)         # 不进行数据复制操作，相当于进行广播: ？+ (3) = (2, 3) ➡️ (2, 3或1) + (3).unsqueeze(0) = (2, 3)，相当于对一个空的张量进行了广播操作

print(x1, x1.shape)

tensor([[1, 2, 3],
        [1, 2, 3]]) torch.Size([2, 3])


In [22]:
# 二维张量扩展
x = torch.tensor([[1], [2], [3]]) # shape:(3, 1)
y = x.expand(3, 4)  # 扩展为 shape=(3, 4) 利用广播的原理扩展第1维

print(y, y.shape)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]) torch.Size([3, 4])


In [23]:
# 使用 -1 保持原维度
x = torch.rand(2, 1, 3)
x1 = x.expand(2, 1, -1) # 第2维保持不变

print(x.shape)
print(x1.shape)

torch.Size([2, 1, 3])
torch.Size([2, 1, 3])


## expand_as

In [25]:
a = torch.rand(3, 1)  # 形状: [3, 1]
b = torch.rand(3, 4)  # 形状: [3, 4]

# 扩展 a 以匹配 b 的形状
a_expanded = a.expand_as(b)  # 等价于 a.expand(3, 4)
print(a_expanded.shape)
c = a_expanded + b

torch.Size([3, 4])


## torch.empty()

在 PyTorch 中，torch.empty() 用于创建未初始化的张量（即张量的值是内存中已有的随机值，未被显式初始化）。这使得它比 torch.zeros() 或 torch.ones() 更快，因为不需要填充特定值。

```python
torch.empty(*size, dtype=None, device=None, requires_grad=False)
```

参数：
- *size：张量的形状（如 (3, 4) 表示 3×4 的矩阵）。
- dtype：数据类型（如 torch.float32，默认）。
- device：存储设备（如 'cpu' 或 'cuda'）。
- requires_grad：是否跟踪梯度（True 或 False）。

In [ ]:
# 1. 创建未初始化的二维张量
import torch

x = torch.empty(3, 4)
print(x)
# 本应该是随机数，但新买的电脑就是干净，全是0.

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
# 2. 指定数据类型和设备
# 创建一个在 GPU 上的 int64 类型张量
x = torch.empty(2, 3, dtype=torch.int64, device='cpu') # 因为写代码用了mac，只有cpu，😆
print(x)
# 输出（随机值）：
# tensor([[0, 0, 0],
#         [0, 0, 0]], device='cuda:0', dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0]])


## tqdm

tqdm 可以接受多个参数来自定义进度条的显示，常用参数如下：
- desc：进度条的前缀说明文字
- total：指定迭代的总次数
- ncols：指定进度条的宽度
- unit：指定进度条的单位
- colour：指定进度条的颜色


In [6]:
from tqdm import tqdm
import time

temp_list = ['file1.txt', 'file2.txt', 'file3.txt']
for i, fname in tqdm(enumerate(temp_list), desc="Processing files", total=len(temp_list), unit="file", colour='green'):
    print(fname)
    time.sleep(1)

Processing files:   0%|          | 0/3 [00:00<?, ?file/s]

file1.txt


Processing files:  33%|███▎      | 1/3 [00:01<00:02,  1.01s/file]

file2.txt


Processing files:  67%|██████▋   | 2/3 [00:02<00:01,  1.01s/file]

file3.txt


Processing files: 100%|██████████| 3/3 [00:03<00:00,  1.01s/file]


## tqdm 与 enumerate 嵌套顺序

在Python中，`tqdm`（进度条库）和`enumerate`（获取索引和值）的嵌套顺序会影响进度条的显示方式和索引值的计算。具体来说：

### **关键区别**
| 顺序               | 进度条总数         | 索引 `i` 的含义          | 示例输出                     |
|--------------------|--------------------|-------------------------|------------------------------|
| `tqdm(enumerate())` | 与数据长度一致     | 数据的真实索引           | `100%|██████████| 4/4 [00:00]` |
| `enumerate(tqdm())` | 与数据长度一致     | 循环计数（与进度条无关） | `100%|██████████| 4/4 [00:00]` |




### **总结**
1. **推荐顺序**：`tqdm(enumerate(data))`  
   - 同时获得真实索引和正确的进度条显示。

2. **特殊场景**：`enumerate(tqdm(data))`  
   - 仅需进度条，不依赖索引与进度的关联（如嵌套循环中的内层进度）。

3. **进度条参数**：  
   - 使用 `total=len(data)` 确保进度条总数正确。
   - 使用 `leave=False` 避免多层进度条残留。

> 经实践验证，两种情况跑出来的效果完全一致，damn!

In [10]:
# 场景 1：tqdm(enumerate())
data = [10, 20, 30, 40]
for i, x in tqdm(enumerate(data), total=len(data)):
    print(f"索引: {i}, 值: {x}")
    time.sleep(0.5)

  0%|          | 0/4 [00:00<?, ?it/s]

索引: 0, 值: 10


 25%|██▌       | 1/4 [00:00<00:01,  1.98it/s]

索引: 1, 值: 20


 50%|█████     | 2/4 [00:01<00:01,  1.98it/s]

索引: 2, 值: 30


 75%|███████▌  | 3/4 [00:01<00:00,  1.98it/s]

索引: 3, 值: 40


100%|██████████| 4/4 [00:02<00:00,  1.98it/s]


In [8]:
# 场景 2：enumerate(tqdm())
data = [10, 20, 30, 40]
for i, x in enumerate(tqdm(data)):
    print(f"索引: {i}, 值: {x}")
    time.sleep(0.5)

  0%|          | 0/4 [00:00<?, ?it/s]

索引: 0, 值: 10


 25%|██▌       | 1/4 [00:00<00:01,  1.98it/s]

索引: 1, 值: 20


 50%|█████     | 2/4 [00:01<00:01,  1.99it/s]

索引: 2, 值: 30


 75%|███████▌  | 3/4 [00:01<00:00,  1.98it/s]

索引: 3, 值: 40


100%|██████████| 4/4 [00:02<00:00,  1.98it/s]


## torch.max()

在 PyTorch 中，`torch.max()` 函数主要用于返回输入张量中的最大值或指定维度上的最大值。它有两种常见用法：


### **1. 返回整个张量的最大值**
#### **语法**
```python
torch.max(input) → scalar
```
- **参数**：`input` 是要处理的张量。
- **返回**：张量中的最大值（标量）。

#### **示例**
```python
import torch

x = torch.tensor([[1, 3, 2], [4, 6, 5]])
max_value = torch.max(x)
print(max_value)  # 输出: tensor(6)
```


### **2. 返回指定维度上的最大值及索引**
#### **语法**
```python
torch.max(input, dim, keepdim=False) → (values, indices)
```
- **参数**：
  - `input`：输入张量。
  - `dim`：指定要缩减的维度（如 `0` 表示按列，`1` 表示按行）。
  - `keepdim`：是否保持输出的维度与输入一致（默认 `False`）。
- **返回**：一个元组 `(values, indices)`，其中：
  - `values`：指定维度上的最大值。
  - `indices`：最大值在原张量中的索引位置。

#### **示例**
```python
x = torch.tensor([[1, 3, 2], [4, 6, 5]])

# 按列（dim=0）计算最大值
max_values, indices = torch.max(x, dim=0)
print("最大值:", max_values)  # 输出: tensor([4, 6, 5])
print("索引:", indices)      # 输出: tensor([1, 1, 1])

# 按行（dim=1）计算最大值
max_values, indices = torch.max(x, dim=1)
print("最大值:", max_values)  # 输出: tensor([3, 6])
print("索引:", indices)      # 输出: tensor([1, 1])
```


### **3. 结合 `keepdim=True` 使用**
当 `keepdim=True` 时，输出的维度与输入相同，只是指定维度的大小变为 1。
```python
x = torch.tensor([[1, 3, 2], [4, 6, 5]])

max_values, indices = torch.max(x, dim=1, keepdim=True)
print("最大值形状:", max_values.shape)  # 输出: torch.Size([2, 1])
print("最大值:", max_values)
# 输出:
# tensor([[3],
#         [6]])
```


### **4. 在实际代码中的应用**
#### **示例：计算 softmax 后的预测类别**
```python
logits = torch.tensor([[1.2, 3.4, 0.8], [2.1, 0.5, 1.8]])
probs = torch.softmax(logits, dim=1)  # 计算概率分布

# 获取预测类别（概率最大的索引）
preds = torch.argmax(probs, dim=1)  # 等价于 torch.max(probs, dim=1)[1]
print("预测类别:", preds)  # 输出: tensor([1, 0])
```


### **5. 与 `torch.argmax()` 的区别**
- **`torch.max()`**：返回最大值 **和** 对应的索引。
- **`torch.argmax()`**：仅返回最大值的索引，不返回值本身。

```python
x = torch.tensor([[1, 3, 2]])

max_value, index = torch.max(x, dim=1)
print("最大值:", max_value)  # 输出: tensor([3])
print("索引:", index)      # 输出: tensor([1])

index = torch.argmax(x, dim=1)
print("索引:", index)      # 输出: tensor([1])
```


### **总结**
| 用法                | 示例                     | 输出                                  |
|---------------------|--------------------------|---------------------------------------|
| 全局最大值          | `torch.max(x)`           | 标量（如 `tensor(6)`）                |
| 按维度最大值        | `torch.max(x, dim=0)`    | 元组 `(values, indices)`              |
| 仅获取索引          | `torch.argmax(x, dim=1)` | 索引张量（如 `tensor([1, 0])`）       |
| 保持维度            | `torch.max(x, dim=1, keepdim=True)` | 保持原维度的最大值张量 |

`torch.max()` 是深度学习中常用的函数，尤其在分类任务中用于获取预测类别。

## Tensor.detach()

在 PyTorch 中，`torch.max()` 函数主要用于返回输入张量中的最大值或指定维度上的最大值。它有两种常见用法：


### **1. 返回整个张量的最大值**
#### **语法**
```python
torch.max(input) → scalar
```
- **参数**：`input` 是要处理的张量。
- **返回**：张量中的最大值（标量）。

#### **示例**
```python
import torch

x = torch.tensor([[1, 3, 2], [4, 6, 5]])
max_value = torch.max(x)
print(max_value)  # 输出: tensor(6)
```


### **2. 返回指定维度上的最大值及索引**
#### **语法**
```python
torch.max(input, dim, keepdim=False) → (values, indices)
```
- **参数**：
  - `input`：输入张量。
  - `dim`：指定要缩减的维度（如 `0` 表示按列，`1` 表示按行）。
  - `keepdim`：是否保持输出的维度与输入一致（默认 `False`）。
- **返回**：一个元组 `(values, indices)`，其中：
  - `values`：指定维度上的最大值。
  - `indices`：最大值在原张量中的索引位置。

#### **示例**
```python
x = torch.tensor([[1, 3, 2], [4, 6, 5]])

# 按列（dim=0）计算最大值
max_values, indices = torch.max(x, dim=0)
print("最大值:", max_values)  # 输出: tensor([4, 6, 5])
print("索引:", indices)      # 输出: tensor([1, 1, 1])

# 按行（dim=1）计算最大值
max_values, indices = torch.max(x, dim=1)
print("最大值:", max_values)  # 输出: tensor([3, 6])
print("索引:", indices)      # 输出: tensor([1, 1])
```


### **3. 结合 `keepdim=True` 使用**
当 `keepdim=True` 时，输出的维度与输入相同，只是指定维度的大小变为 1。
```python
x = torch.tensor([[1, 3, 2], [4, 6, 5]])

max_values, indices = torch.max(x, dim=1, keepdim=True)
print("最大值形状:", max_values.shape)  # 输出: torch.Size([2, 1])
print("最大值:", max_values)
# 输出:
# tensor([[3],
#         [6]])
```


### **4. 在实际代码中的应用**
#### **示例：计算 softmax 后的预测类别**
```python
logits = torch.tensor([[1.2, 3.4, 0.8], [2.1, 0.5, 1.8]])
probs = torch.softmax(logits, dim=1)  # 计算概率分布

# 获取预测类别（概率最大的索引）
preds = torch.argmax(probs, dim=1)  # 等价于 torch.max(probs, dim=1)[1]
print("预测类别:", preds)  # 输出: tensor([1, 0])
```


### **5. 与 `torch.argmax()` 的区别**
- **`torch.max()`**：返回最大值 **和** 对应的索引。
- **`torch.argmax()`**：仅返回最大值的索引，不返回值本身。

```python
x = torch.tensor([[1, 3, 2]])

max_value, index = torch.max(x, dim=1)
print("最大值:", max_value)  # 输出: tensor([3])
print("索引:", index)      # 输出: tensor([1])

index = torch.argmax(x, dim=1)
print("索引:", index)      # 输出: tensor([1])
```


### **总结**
| 用法                | 示例                     | 输出                                  |
|---------------------|--------------------------|---------------------------------------|
| 全局最大值          | `torch.max(x)`           | 标量（如 `tensor(6)`）                |
| 按维度最大值        | `torch.max(x, dim=0)`    | 元组 `(values, indices)`              |
| 仅获取索引          | `torch.argmax(x, dim=1)` | 索引张量（如 `tensor([1, 0])`）       |
| 保持维度            | `torch.max(x, dim=1, keepdim=True)` | 保持原维度的最大值张量 |

`torch.max()` 是深度学习中常用的函数，尤其在分类任务中用于获取预测类别。

## 计算 acc 和 loss 时的细节区别

### **为什么 `train_acc/len(train_set)` 和 `train_loss/len(train_loader)` 除以不同的长度？**
这与 **`train_set` 和 `train_loader` 的含义**以及 **准确率和损失的计算方式** 有关：

#### **1. 数据集长度 vs 数据加载器长度**
- **`train_set`**：表示训练集的**总样本数**（例如，1000个样本）。
- **`train_loader`**：表示训练集的数据加载器，通常会将数据分成多个**批次**（batch）。假设每个批次有32个样本，则 `len(train_loader)` 为 **总批次数**（例如，1000/32 ≈ 32个批次）。


#### **2. 准确率和损失的计算逻辑**
- **准确率（Accuracy）**：是 **正确预测的样本数 / 总样本数**。
  - `train_acc` 累加的是每个批次中正确预测的样本数（例如，32个样本中预测对了28个）。
  - 因此，需要除以 **总样本数 `len(train_set)`** 来得到平均准确率。

- **损失（Loss）**：是 **每个批次的平均损失之和**。
  - `train_loss` 累加的是每个批次的**平均损失**（即 `loss.item()`，一个批次内所有样本的平均损失）。
  - 因此，需要除以 **总批次数 `len(train_loader)`** 来得到所有批次的平均损失。


## np.concatenate

在 Python 的 NumPy 库中，np.concatenate函数用于将多个数组沿指定轴连接成一个新数组。

In [2]:
# 一维数组的连接
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b), axis=0)
print(result)

[1 2 3 4 5 6]


In [4]:
# 二维数组的连接
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# 沿第0维拼接
result = np.concatenate((a, b), axis=0)
print(result)

# 沿第1维拼接
result2 = np.concatenate((a, b), axis=1)
print(result2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [5]:
# 多个数组拼接要注意，连接的维度必须保持一致